In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df=pd.read_csv("homeprices.csv")
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

import math
median_bedrooms=math.ceil(df.bedrooms.median())
median_bedrooms

In [15]:
df_bedrooms=df.bedrooms.fillna(median_bedrooms)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
import math
median_bedrooms=math.ceil(df.bedrooms.median())
median_bedrooms

4

In [17]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [19]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

from sklearn import linearmodel

In [28]:
from sklearn import linear_model
reg=linear_model.LinearRegression()

In [29]:
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [32]:
reg.predict([[4200,10,10]])

C:\Users\S7061\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([893556.87971543])

In [33]:
d=pd.read_csv("hiring.csv")
d

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [58]:
d['test_score(out of 10)']=d['test_score(out of 10)'].fillna(0)
d

,experience,test_score(out of 10),interview_score(out of 10),salary($),test_score
0,zero,8.0,9,50000,8.0
1,zero,8.0,6,45000,8.0
2,five,6.0,7,60000,6.0
3,two,10.0,10,65000,10.0
4,seven,9.0,6,70000,9.0
5,three,7.0,10,62000,7.0
6,ten,0.0,7,72000,0.0
7,eleven,7.0,8,80000,7.0

In [59]:
d

,experience,test_score(out of 10),interview_score(out of 10),salary($),test_score
0,zero,8.0,9,50000,8.0
1,zero,8.0,6,45000,8.0
2,five,6.0,7,60000,6.0
3,two,10.0,10,65000,10.0
4,seven,9.0,6,70000,9.0
5,three,7.0,10,62000,7.0
6,ten,0.0,7,72000,0.0
7,eleven,7.0,8,80000,7.0

In [65]:


from word2number import w2n
d['experience'] = d['experience'].apply(w2n.word_to_num)
d

,experience,test_score(out of 10),interview_score(out of 10),salary($),test_score
0,0,8.0,9,50000,8.0
1,0,8.0,6,45000,8.0
2,5,6.0,7,60000,6.0
3,2,10.0,10,65000,10.0
4,7,9.0,6,70000,9.0
5,3,7.0,10,62000,7.0
6,10,0.0,7,72000,0.0
7,11,7.0,8,80000,7.0

In [62]:
d.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)', 'test_score'],
      dtype='object')

In [64]:
d.columns = d.columns.str.strip()

In [74]:
reg.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])

LinearRegression()

In [75]:
reg.predict([[2,9,6]])

C:\Users\S7061\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([52688.25222797])

In [76]:
reg.predict([[12,10,10]])

C:\Users\S7061\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([92940.63332619])